---
# See:
#   - https://github.com/solo-io/unik/blob/master/docs/install.md

- name: Import docker roles
  import_role:
    name: docker

- name: Install prerequisites packages
  apt:
    name:
      - git
      - go-bindata
      - jq
      - make
      - qemu-system

- name: Download Golang tarball
  get_url:
    url: "{{ golang_location }}"
    dest: "/usr/local/src/{{ golang_tarball }}"
    checksum: "{{ golang_checksum }}"

- name: Install Golang
  become: true
  become_user: "{{ dev_user }}"
  unarchive:
    src: "/usr/local/src/{{ golang_tarball }}"
    dest: "{{ homedir }}"
    copy: no
    creates: "{{ homedir }}/go"

- name: Checkout solo-io/unik repository
  become: true
  become_user: "{{ dev_user }}"
  git:
    repo: "https://github.com/solo-io/unik.git"
    dest: "{{ homedir }}/src/unik"
