---

- name: Deploy configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: wheel
    mode: '0644'
  with_items:
    - {src: repositories.conf, dest: /usr/pkg/etc/pkgin/repositories.conf}

- name: Update repository cache
  pkgin:
    update_cache: yes
