---
# See:
#   - https://docs.docker.com/engine/install/debian/
#   - https://docs.docker.com/engine/install/linux-postinstall/

- name: Update the apt pacakge index and install packages to allow apt to use a repository over HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes
    state: latest

- name: Add Docker’s official GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "{{ docker_url }}/gpg"
    state: present

- name: Set up the stable repository
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_url }} {{ ansible_distribution_release }} stable"

- name: Install the latest version of Docker Engine and containerd
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Create the docker group
  group:
    name: "{{ docker_group }}"
    state: present

- name: Add your user to the docker group
  user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  with_items: "{{ your_users }}"

- name: Configure Docker to start on boot
  systemd:
    name: docker
    state: started
    enabled: yes
