---

- name: Bootstrap NetBSD host for Ansible
  gather_facts: no
  hosts: netbsd_bootstrap
  roles:
    - bootstrap

- name: Setup pkgsrc & pkgsrc-wip in NetBSD host
  hosts: netbsd_pkgsrc
  roles:
    - pkgsrc_wip
